jwt:
  secret: ahjnfshjkfjksdhfjlkdsfjkhsdjkfhsdufjghujas
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: create-drop
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG